name = "femphilic/requestly"
version = "0.2.2"
description = "An open-source library for making type-safe requests in Luau."
authors = ["femphilic <femphilic.com@gmail.com> (https://femphilic.com)"]
repository = "https://github.com/femphilic/requestly"
license = "MIT"
includes = ["pesde.toml", "README.md", "LICENSE", "src/lune/**/*.luau"]

[target]
environment = "lune"
lib = "src/lune/init.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[engines]
pesde = "^0.7.0"
lune = "^0.10.4"
