# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
luau-lsp = "JohnnyMorganz/luau-lsp@1.54.0"
rojo = "rojo-rbx/rojo@7.6.0"
selene = "Kampfkarren/selene@0.29.0"
stylua = "JohnnyMorganz/stylua@2.3.0"
wally = "UpliftGames/wally@0.3.2"
lune = "lune-org/lune@0.10.4"
