[package]
name = "femphilic/requestly"
description = "An open-source library for making type-safe requests in Luau."
license = "MIT"
authors = ["femphilic <femphilic.com@gmail.com> (https://femphilic.com)"]
repository = "https://github.com/femphilic/requestly"
exclude = ["**"]
include = [
  "src/roblox",
  "src/roblox/**",
  "wally.toml",
  "wally.lock",
  "default.project.json",
  "LICENSE",
  "README.md",
]
version = "0.2.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "server"
